### ISSUE TITLE
Single file hub

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/ucsc-hub-js#17]
Ref https://genome.ucsc.edu/goldenPath/help/hgTracksHelp.html#UseOneFile

Example https://genome.ucsc.edu/goldenPath/help/examples/hubExamples/hubUseOneFile/singleFileHubExample.txt

Just a curiosity from browsing ucsc

**Comment by rbuels** [comment]
Looking for clarification, do you mean that we need to add support for useOneFile?

**Comment by cmdcolin** [comment]
Ya, it'd likely be a new feature
